Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  config.vm.define "kubemaster" do |kubemaster|
    kubemaster.vm.box = "bento/ubuntu-16.04"
	kubemaster.vm.network "private_network", ip: "192.168.56.2"
	kubemaster.vm.provider "vmware_fusion" do |v|
            vb.name = "kubemaster"
            vb.memory = 2048
            vb.cpus = 2
        end
	kubemaster.vm.hostname = "kubemaster"
	kubemaster.vm.provision "shell", path: "kubemaster-init.sh"
  end

  config.vm.define "kubenode1" do |kubenode1|
    kubenode1.vm.box = "bento/ubuntu-16.04"
	kubenode1.vm.network "private_network", ip: "192.168.56.3"
        kubenode1.vm.provider "vmware_fusion" do |v|
            vb.name = "kubenode1"
            vb.memory = 1028
            vb.cpus = 2
        end
        kubenode1.vm.hostname = "kubenode1"
	kubenode1.vm.provision "shell", path: "kubenode1-init.sh"
  end

  config.vm.define "kubenode2" do |kubenode2|
    kubenode2.vm.box = "ubuntu/bionic64"
        kubenode2.vm.network "private_network", ip: "192.168.56.4"
        kubenode2.vm.provider "vmware_fusion" do |v|
            vb.name = "kubenode2"
            vb.memory = 1028
            vb.cpus = 2
        end
        kubenode2.vm.hostname = "kubenode2"
	kubenode2.vm.provision "shell", path: "kubenode2-init.sh"
  end
end
